# Generated by Django 5.0.8 on 2025-09-05 06:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("stores", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductStore",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.PositiveIntegerField(
                        default=0, help_text="Current physical stock quantity"
                    ),
                ),
                (
                    "reserved_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Quantity reserved for orders"
                    ),
                ),
                (
                    "minimum_stock_level",
                    models.PositiveIntegerField(
                        default=0, help_text="Minimum stock level for reorder alerts"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_inventories",
                        to="products.product",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_inventories",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Store Inventory",
                "verbose_name_plural": "Product Store Inventories",
                "db_table": "inventory_product_store",
                "ordering": ["-created_at"],
                "unique_together": {("product", "store")},
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("INBOUND", "Inbound - Stock received"),
                            ("OUTBOUND", "Outbound - Stock sold/used"),
                            ("TRANSFER", "Transfer - Stock moved between stores"),
                            ("ADJUSTMENT", "Adjustment - Stock count correction"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(help_text="Positive for increases, negative for decreases"),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Reference number (PO, SO, Transfer ID, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional notes about the movement"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_product_store",
                    models.ForeignKey(
                        blank=True,
                        help_text="For transfers, the destination ProductStore",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transfers",
                        to="inventory.productstore",
                    ),
                ),
                (
                    "product_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="inventory.productstore",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Movement",
                "verbose_name_plural": "Stock Movements",
                "db_table": "inventory_stock_movement",
                "ordering": ["-created_at"],
            },
        ),
    ]
