[tool.black]
line-length = 100
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 100
force_single_line = false
known_first_party = ["accounts","brands","stores","products","inventory","orders","pricing","audit","common"]
